### POST request to employee server
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "eeee",
  "lastName": "ffff",
  "email": "eeee@email.com"
}

### GET Employee by id
GET http://localhost:8080/api/employees/2


### GET all Employee
GET http://localhost:8080/api/employees

### PUT Employee
PUT http://localhost:8080/api/employees/4
Content-Type: application/json

{
  "firstName": "ee22",
  "lastName": "ff22",
  "email": "ee22@email.com"
}